version: "3.3"
services:
  angular:
    build: ./angular
    container_name: angular
    restart: always
    ports:
      - 4200:4200
    links:
      - spring

  spring:
    build: ./spring
    container_name: spring
    ports:
      - 8080:8080
    environment:
      - MYSQL_SERVER_NAME=mysql
      - MYSQL_DB=restaurantDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    depends_on:
      - mysql
    restart: always
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=restaurantDB
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
