server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/restaurantDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: '1234'
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    generate-ddl: true
  devtools:
    livereload:
      enabled: true